### PR TITLE
use ipfsapi in pubsub and tests improvements

### PR DESCRIPTION
**Pull request by strdn**
launch with:
rostest -r robonomics_liability liability.test --text

### CODE REVIEW

**Comment by akru** [comment]
@strdn could you fix Travis build here?

**Comment by strdn** [comment]
@akru, I think that ROS tests must be disabled on Travis cause most of them requires ROS core and another things such as ipfs and parity. I suggest discussing the process of continuous testing in another environment.

**Comment by akru** [comment]
Ok, just use Travis to check correctness of stack directory structure, dependencies and ‘package’ files.

**Comment by strdn** [comment]
@akru please see again.

**Pull request merged**
